name: MSBuild

on:
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Decode the Pfx
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        [IO.File]::WriteAllBytes(".\TemporaryKey.pfx", $pfx_cert_byte)

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget.exe restore ContextMenuCustom -SolutionDirectory ContextMenuCustom
      
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:restore ContextMenuCustom\ContextMenuCustomApp\ContextMenuCustomApp.csproj

    - name: Build ContextMenuCustomHost
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ContextMenuCustom\ContextMenuCustomHost\ContextMenuCustomHost.vcxproj /m /p:configuration="release" /p:SolutionDir=../  /p:platform="x64"
      
    - name: Build ContextMenuCustomDevPackage
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ContextMenuCustom\ContextMenuCustomDevPackage\ContextMenuCustomDevPackage.wapproj /m /p:configuration="release"   /p:platform="x64" /p:PackageCertificateKeyFile=".\TemporaryKey.pfx" /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
    
    - name: Build ContextMenuCustomGithubPackage
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ContextMenuCustom\ContextMenuCustomGithubPackage\ContextMenuCustomGithubPackage.wapproj /m /p:configuration="release"   /p:platform="x64" /p:PackageCertificateKeyFile=".\TemporaryKey.pfx" /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
