name: MSBuild

on:
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}\ContextMenuCustom
      run: nuget restore ContextMenuCustom.sln

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}\ContextMenuCustom
      run: msbuild ContextMenuCustomHost\ContextMenuCustomHost.vcxproj /m /p:configuration="release"   /p:platform="x64"
      
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}\ContextMenuCustom
      run: msbuild ContextMenuCustomPackage\ContextMenuCustomPackage.wapproj /m /p:configuration="release"   /p:platform="x64"
